"""empty message

Revision ID: 04cef39df976
Revises: 843d74267808
Create Date: 2019-03-12 11:04:51.129673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

from application.models import LocalPlan


# revision identifiers, used by Alembic.
revision = '04cef39df976'
down_revision = '843d74267808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emerging_fact', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('fact', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('local_plan', sa.Column('adopted_date', sa.Date(), nullable=True))
    op.add_column('local_plan', sa.Column('published_date', sa.Date(), nullable=True))
    op.add_column('local_plan', sa.Column('sound_date', sa.Date(), nullable=True))
    op.add_column('local_plan', sa.Column('submitted_date', sa.Date(), nullable=True))

    connection = op.get_bind()
    SessionMaker = sessionmaker(bind=connection.engine)
    session = SessionMaker(bind=connection)
    for plan in session.query(LocalPlan):
        for s in plan.states:
            if s[0] == 'published':
                plan.published_date = s[1]
            elif s[0] == 'submitted':
                plan.submitted_date = s[1]
            elif s[0] == 'sound':
                plan.sound_date = s[1]
            elif s[0]== 'adopted':
                plan.adopted_date = s[1]
        session.add(plan)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_plan', 'submitted_date')
    op.drop_column('local_plan', 'sound_date')
    op.drop_column('local_plan', 'published_date')
    op.drop_column('local_plan', 'adopted_date')
    op.drop_column('fact', 'created_date')
    op.drop_column('emerging_fact', 'created_date')
    # ### end Alembic commands ###
