"""empty message

Revision ID: 09265b125512
Revises: 68fd598458dc
Create Date: 2019-07-16 10:04:55.489413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09265b125512"
down_revision = "68fd598458dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "local_plan",
        sa.Column("local_development_framework_number", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("local_plan", "local_development_framework_number")
    # ### end Alembic commands ###
