"""empty message

Revision ID: 10646a34f138
Revises: 
Create Date: 2019-02-14 11:32:18.501790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10646a34f138'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_authority',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_plan',
    sa.Column('local_plan', sa.String(), nullable=False),
    sa.Column('planning_policy_url', sa.String(), nullable=True),
    sa.Column('planning_authority_id', sa.String(length=64), nullable=False),
    sa.Column('states', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('number_of_houses', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planning_authority_id'], ['planning_authority.id'], ),
    sa.PrimaryKeyConstraint('local_plan')
    )
    op.create_table('plan_document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_document_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('local_plan_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['local_plan_id'], ['local_plan.local_plan'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_document')
    op.drop_table('local_plan')
    op.drop_table('planning_authority')
    # ### end Alembic commands ###
