"""empty message

Revision ID: 21cc82392c1a
Revises: 849eba2d4d81
Create Date: 2019-02-28 20:13:34.821009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cc82392c1a'
down_revision = '849eba2d4d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_plan', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_plan', 'title')
    # ### end Alembic commands ###
