"""empty message

Revision ID: 24ff4910d1f0
Revises: 500a286fb15c
Create Date: 2019-04-30 12:13:04.096153

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

Session = sessionmaker()
Base = declarative_base()

# revision identifiers, used by Alembic.
revision = '24ff4910d1f0'
down_revision = '500a286fb15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_plan', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('local_plan', sa.Column('updated_date', sa.DateTime(), nullable=True))

    class LocalPlan(Base):
        __tablename__ = 'local_plan'

        id = sa.Column(UUID(as_uuid=True), primary_key=True)
        created_date = sa.Column(sa.Date())


    bind = op.get_bind()
    session = Session(bind=bind)

    for plan in session.query(LocalPlan):
        plan.created_date = datetime.utcnow()
        session.add(plan)
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_plan', 'updated_date')
    op.drop_column('local_plan', 'created_date')
    # ### end Alembic commands ###
