"""empty message

Revision ID: 30810438669a
Revises: e8789491fbf6
Create Date: 2019-02-27 19:46:23.574649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30810438669a'
down_revision = 'e8789491fbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unchecked_document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('planning_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['planning_authority_id'], ['planning_authority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unchecked_document')
    # ### end Alembic commands ###
