"""empty message

Revision ID: 3e60ac0fe412
Revises: 
Create Date: 2019-02-13 15:04:31.386710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e60ac0fe412'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_authority',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local_plan',
    sa.Column('local_plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('planning_policy_url', sa.String(), nullable=True),
    sa.Column('planning_authority_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['planning_authority_id'], ['planning_authority.id'], ),
    sa.PrimaryKeyConstraint('local_plan', 'status')
    )
    op.create_table('plan_document',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_document_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('local_plan_id', sa.String(), nullable=False),
    sa.Column('local_plan_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['local_plan_id', 'local_plan_status'], ['local_plan.local_plan', 'local_plan.status'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_document')
    op.drop_table('local_plan')
    op.drop_table('planning_authority')
    # ### end Alembic commands ###
