"""empty message

Revision ID: 4d214ec6427e
Revises: 95d57b76c8c0
Create Date: 2019-03-19 12:01:29.303386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d214ec6427e'
down_revision = '95d57b76c8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'to_year')
    op.drop_column('fact', 'from_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('from_year', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('fact', sa.Column('to_year', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
