"""empty message

Revision ID: 500a286fb15c
Revises: 8179554f9881
Create Date: 2019-04-10 10:58:17.707905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500a286fb15c'
down_revision = '8179554f9881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_plan', 'start_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_plan', sa.Column('start_year', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
