"""empty message

Revision ID: 5b9c80bae971
Revises: 04cef39df976
Create Date: 2019-03-12 16:11:22.262558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b9c80bae971'
down_revision = '04cef39df976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_delivery_test',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('from_year', sa.Date(), nullable=True),
    sa.Column('to_year', sa.Date(), nullable=True),
    sa.Column('homes_required', sa.Integer(), nullable=True),
    sa.Column('homes_delivered', sa.Integer(), nullable=True),
    sa.Column('planning_authority_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['planning_authority_id'], ['planning_authority.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planning_authority', sa.Column('ons_code', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_authority', 'ons_code')
    op.drop_table('housing_delivery_test')
    # ### end Alembic commands ###
