"""empty message

Revision ID: 76a6f18abd2b
Revises: 24ff4910d1f0
Create Date: 2019-04-30 15:17:26.216436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()
Base = declarative_base()

# revision identifiers, used by Alembic.
revision = '76a6f18abd2b'
down_revision = '24ff4910d1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_plan', sa.Column('deleted', sa.Boolean(), nullable=True))

    class LocalPlan(Base):
        __tablename__ = 'local_plan'

        id = sa.Column(UUID(as_uuid=True), primary_key=True)
        deleted = sa.Column(sa.Boolean())

    bind = op.get_bind()
    session = Session(bind=bind)

    for plan in session.query(LocalPlan):
        plan.deleted = False
        session.add(plan)
        session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('local_plan', 'deleted')
    # ### end Alembic commands ###
