"""empty message

Revision ID: d39988708544
Revises: de9a31fdc552
Create Date: 2019-03-05 10:26:40.706022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39988708544'
down_revision = 'de9a31fdc552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('fact', sa.String(), nullable=True))
    op.add_column('fact', sa.Column('fact_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'fact_type')
    op.drop_column('fact', 'fact')
    # ### end Alembic commands ###
