"""empty message

Revision ID: d6d88ca27215
Revises: 10646a34f138
Create Date: 2019-02-14 15:00:26.324660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d88ca27215'
down_revision = '10646a34f138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_authority', sa.Column('plan_policy_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_authority', 'plan_policy_url')
    # ### end Alembic commands ###
