"""empty message

Revision ID: e21e477c9337
Revises: de3e63a5fc18
Create Date: 2019-03-26 11:16:30.393730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21e477c9337'
down_revision = 'de3e63a5fc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_local_plan_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key('document_local_plan_id_fkey', 'document', 'local_plan', ['local_plan_id'], ['id'])
    op.alter_column('local_plan', 'local_plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planning_authority_plan', 'local_plan_id_old',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('planning_authority_plan_planning_authority_id_fkey', 'planning_authority_plan', type_='foreignkey')
    op.drop_constraint('planning_authority_plan_local_plan_id_fkey', 'planning_authority_plan', type_='foreignkey')
    op.create_foreign_key('planning_authority_plan_planning_authority_id_fkey', 'planning_authority_plan', 'planning_authority', ['planning_authority_id'], ['id'])
    op.create_foreign_key('planning_authority_plan_local_plan_id_fkey', 'planning_authority_plan', 'local_plan', ['local_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('planning_authority_plan_local_plan_id_fkey', 'planning_authority_plan', type_='foreignkey')
    op.drop_constraint('planning_authority_plan_planning_authority_id_fkey', 'planning_authority_plan', type_='foreignkey')
    op.create_foreign_key('planning_authority_plan_local_plan_id_fkey', 'planning_authority_plan', 'local_plan', ['local_plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('planning_authority_plan_planning_authority_id_fkey', 'planning_authority_plan', 'planning_authority', ['planning_authority_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('document_local_plan_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key('document_local_plan_id_fkey', 'document', 'local_plan', ['local_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
