"""empty message

Revision ID: e8789491fbf6
Revises: d6d88ca27215
Create Date: 2019-02-27 13:52:00.576273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8789491fbf6'
down_revision = 'd6d88ca27215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_authority', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_authority', 'website')
    # ### end Alembic commands ###
