"""empty message

Revision ID: f05f05b22995
Revises: 8b06da1ec5da
Create Date: 2019-03-26 16:23:25.481188

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05f05b22995'
down_revision = '8b06da1ec5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_authority', sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_authority', 'geometry')
    # ### end Alembic commands ###
