"""add govt organisation

Revision ID: f3316d85a579
Revises: a27d34659df8
Create Date: 2023-04-28 14:22:16.267137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3316d85a579"
down_revision = "a27d34659df8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planning_authority", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("government_organisation", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("planning_authority", schema=None) as batch_op:
        batch_op.drop_column("government_organisation")
    # ### end Alembic commands ###
